civiform/docs

docs/contributor-guide/developer-guide/getting-started.md
Linux users need to install the docker compose v2 plugin 
This will only be necessary [until compose v2 is GA](https://docs.docker.com/compose/cli-command/#transitioning-to-ga-for-compose-v2)
=> Add docker compose v2 instruction

docs/it-manual/sre-playbook/initial-deployment.md
The existing docs had broken links and wasn't clear about aws deploys
=> Fix links to seattle deployment & add link to terraform docs

docs/it-manual/sre-playbook/terraform-deploy-system.md
1. `bin/doctor` requires passing tag at the moment. So adding it there.
2. Typo fixes.
=> Few fixes to terraform deployment guide.

docs/contributor-guide/developer-guide/testing.md
Also re-order content of browser test docs. 
Also remove existing screenshot debugging tip. I think this is redundant since we have formal support for screenshot tests, and we can just use that or run in debug mode to debug.
=> Add screenshot browser test instructions

docs/contributor-guide/developer-guide/technical-contribution-guide.md
The additional comments make it clear to users that are inexperienced with git that the main branch is used for syncing and they make the guide more accurate for branches other than the very first one ever created.
=> Update technical contribution guide

docs/contributor-guide/developer-guide/dev-testing.md, docs/contributor-guide/developer-guide/file-storage-backend.md, docs/contributor-guide/developer-guide/getting-started.md
This matches what is used in tests and official Localstack docs.
=> Update docs to use localhost.localstack.cloud host for accessing localstack

docs/contributor-guide/developer-guide/getting-started.md
I was frustrated by the issue above with the `.routes` package not being recognized by IntelliJ, which made a significant number of my files have red lines suggesting they do not compile. The workaround described in this PR fixes that.
=> Add IntelliJ troubleshooting for routes issue

docs/contributor-guide/developer-guide/testing.md
Adds running bin/run-browser-test-env --local for browser local test debugging, as added by https://github.com/civiform/civiform/pull/4396.
=> Update testing.md with --local flag

docs/contributor-guide/developer-guide/releasing.md, docs/governance-and-management/project-management/on-call-guide/README.md, docs/it-manual/sre-playbook/upgrading-to-a-new-release.md
Edits to the Oncall and Release docs including:
- fixed links
- removed outdated info
- added additional steps to Oncall responsibilities
=> updating oncall docs

docs/it-manual/sre-playbook/monitoring.md
Copy / pasting the URL from the prometheus ID is a bit confusing. Instead, we can simply rename the data source to what the json file expects.
=> Update monitoring instructions

docs/contributor-guide/developer-guide/feature-flags.md
With the implementation of server variable auto-generation, passing the server vars through the deploy system is no longer necessary. This PR updates the docs to reflect that.
=> remove steps to add feature flags to deploy code

docs/user-manual/civiform-admin-guide/download-exported-data.md, docs/user-manual/civiform-admin-guide/manage-questions.md
Clarify description of question data export settings
Updates the text admins see when setting data privacy settings for questions, to clarify that they only affect the demography export, not the API.
This is part of https://github.com/civiform/civiform/issues/5347
=> Update demography export settings text

docs/it-manual/api/program-applications.md
The current output from the API doesn't include this and I don't recall that it ever did.
=> Removing 'updated_at' from the api sample output

docs/it-manual/sre-playbook/email-configuration.md
`CIVIC_ENTITY_SUPPORT_EMAIL_ADDRESS` is now called `SUPPORT_EMAIL_ADDRESS` and is set in the Admin Settings Panel, not the deployment config.
Related to https://github.com/civiform/civiform/issues/6636
=> Update reference to CIVIC_ENTITY_SUPPORT_EMAIL_ADDRESS

docs/it-manual/sre-playbook/server-environment-variables/README.md
There's been some confusion recently (eg: https://github.com/civiform/civiform/issues/6680) about how to set values for admin writeable variables. I'm adding some info here about it and the other variable "modes" for folks to reference going forward.
Related to https://github.com/civiform/civiform/issues/6687
=> Add info about server var modes

docs/it-manual/api/program-applications.md
Remove warning about historical questions from API docs
Now that https://github.com/civiform/civiform/issues/5018 is complete and all historical questions are included in the API response, we can remove the warning and replace it with a note about why we include all historical questions.
=> Remove warning about historical questions from API docs

docs/governance-and-management/governance/communication.md
The new-contributions channel is archived so it shouldn't be listed anymore.
=> Remove the new-contributions channel from the communication guidelines

docs/governance-and-management/governance/communication.md
This channel is archived so it should not be listed.
=> Remove story-acceptance channel from communications guide

docs/governance-and-management/governance/governance-processes.md
Google employees can't create or move docs in the drive if they've joined with their Google emails. This has caused some confusion, so we want to update the docs to clarify. More context in Slack: https://civiform.slack.com/archives/C01QKN2UNMA/p1713805259180809
=> Add note about google employees creating docs

docs/it-manual/sre-playbook/server-environment-variables/README.md
With the changes introduced in https://github.com/civiform/cloud-deploy-infra/pull/318, including ADMIN_WRITEABLE vars in the deploy config will throw an error. This PR updates the docs to reflect this.
=> Update notes on admin writeable vars

docs/governance-and-management/project-management/on-call-guide/README.md
Added more detailed instructions for what the person on call should do when they receive a security vulnerability advisory.
=> Update On Call docs with more instructions for security vulnerabilities

docs/it-manual/api/program-applications.md
Add API docs for file_urls (in preparation for multiple file uploads.)
This documents both properties for now, using a single file. Once we launch, we'll remove file_key and we'll also change the example to include multiple files.
=> Add API docs for file_urls

docs/user-manual/civiform-admin-guide/program-migration.md
Adding a note that we do not yet support visibility or eligibility predicates dependent on service area validation.
Related to https://github.com/civiform/civiform/issues/8450
=> Add note about service area validation error

website/public/about/index.html, website/public/faq/index.html, website/src/about.md, website/src/faq.md
Update "Get Started" link to /getstarted-new and add "Implementation Guide" link in FAQ "How can I get CiviForm in my community?" answer
Update "Get Started" link to /getstarted-new in About page button
=> Update links in FAQ and About buttons

website/public/about/index.html, website/public/contact-new/index.html, website/public/contact/index.html, website/public/deploymentguide/index.html, website/public/faq/index.html, website/public/getstarted-new/index.html, website/public/implementation-guide/index.html, website/public/index.html, website/public/learnmore/index.html, website/public/news/index.html, website/src/_includes/layouts/navigation.njk, website/src/getstarted-new.md
Changed case for Get Started in nav bar and Get Started page from "Get started" to "Get Started"
Changed case for "Implementation Guide" in button on "Get Started" page
=> Change case for Get Started in nav bar

website/package-lock.json
npm install noted 3 vulnerabilities
```
micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix`
node_modules/micromatch
path-to-regexp  4.0.0 - 6.2.2
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix available via `npm audit fix`
node_modules/path-to-regexp
rollup  4.0.0 - 4.22.3
Severity: high
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS - https://github.com/advisories/GHSA-gcx4-mw62-g8wm
fix available via `npm audit fix`
node_modules/rollup
3 vulnerabilities (1 moderate, 2 high)
To address all issues, run:
npm audit fix
```
After upgrading these we will no …
=> Update versions to fix vulnerabilities

docs/user-manual/civiform-admin-guide/program-migration.md
Added the "pre-screener" setting to the list of settings not migrated.
Related to https://github.com/civiform/civiform/issues/8652
=> Add note about pre-screener not being migrated

docs/user-manual/onboarding-guide/civic-entity-staffing-overview.md
Remove the extraneous phrase "and definitions", and fix the grammar of the phrase "program applications".
=> Fix typos in civic-entity-staffing-overview.md.

website/public/deploymentguide copy/index.html, website/public/implementation-guide/index.html, website/public/index.html, website/public/tech-guide/index.html, website/public/techguide/index.html, website/src/implementation-guide.md, website/src/index.md, website/src/tech-guide.md
Publish draft CiviForm Technical Readiness Guide
Update link in Implementation Guide to point to new Tech Readiness Guide
Fix the current homepage buttons “Learn more” and “Get started” to point to new “Learn more” and “Get started” pages
=> Add draft Tech Readiness Guide and fix nits

docs/user-manual/civiform-admin-guide/program-migration.md
Update the program migration docs to remove any references to the `PROGRAM_MIGRATION_ENABLED` feature flag. We are turning the flag on by default so we no longer need to reference it.
Related to https://github.com/civiform/civiform/issues/7088
=> [Program Migration] Remove references to PROGRAM_MIGRATION_ENABLED feature flag

docs/it-manual/api/program-applications.md
application_note was exposed in the api results. syncing docs.
=> Adding application_note to api documentation

docs/it-manual/sre-playbook/upgrading-to-a-new-release.md
Updated our release info to reflect our new policy of publishing a release on Tuesdays or Wednesdays
Based on discussion in our eng weekly meeting on 3/3/25. [See notes](https://docs.google.com/spreadsheets/d/1jXuOWl9TxssHh3A1AkmKi2gva9LRUhE0PQStJa-4yWs/edit?gid=1246619714#gid=1246619714)
Fyi I didn't update the instructions [here](https://github.com/civiform/docs/blob/5e4bcf07814ce46323a68b70156013afb379dabe/docs/governance-and-management/project-management/on-call-guide/README.md#L45) because they say to draft a release by Tuesday, 12pm PT which is still true. The only thing changing is the criteria for when we publish a release.
Corresponding internal wiki update [here](https://github.com/civiform/civiform/wiki/Releasing/_compare/10902d3af4b4927cd8555958d222d4c1316edf74)
Corresponding …
=> Update release info to say Tuesday or Wednesday

docs/user-manual/civiform-admin-guide/manage-trusted-intermediaries.md
This doc update is a response to https://github.com/civiform/civiform/pull/10098, which requires that new TI group names be unique from existing TI group names. Existing groups are not affected.
=> Add note about requiring unique group names

docs/it-manual/api/program-applications.md
Timestamps were added to the `fromDate` and `toDate` params in list applications API on #10636. This updates the documentation for it
Fixes [#5483](https://github.com/civiform/civiform/issues/5483)
=> Add time filter to list applications API documentation

docs/it-manual/api/program-applications.md
Revision state parameter was added to list applications API in [#10747](https://github.com/civiform/civiform/pull/10747). This updates the documentation for it
Part of [#499](https://github.com/civiform/civiform/issues/499)
=> Add revision state param to applications API documentation
