website/.eleventy.js, website/public/index.html, website/src/_includes/layouts/base.njk, website/src/_includes/layouts/home.njk, website/src/index.md
e82f1ddbcd80ee2e214c1745ec8cbc9d47b89ddb Also adds nunjucks config options which gets rid of extra whitespace in rendered HTML.
=> Break out homepage template from base template

website/public/about/index.html, website/public/contact/index.html, website/public/css/index.css, website/public/index.html, website/src/_includes/layouts/base.njk, website/src/css/index.scss, website/src/index.md
=> Fix mobile layout.

docs/contributor-guide/developer-guide/getting-started.md
Added a Code coverage section and how to run and view the coverage report
=> Update README to include test coverage instructions

docs/contributor-guide/developer-guide/getting-started.md
=> Fix broken logback.xml link

docs/contributor-guide/developer-guide/technical-contribution-guide.md
This changed after the repo migration.
=> Update round robin alias to the correct group

docs/contributor-guide/developer-guide/file-storage-backend.md, docs/contributor-guide/developer-guide/getting-started.md
This allows file upload and login to work with your local server.
=> Update docs with local IP routing instructions

docs/it-manual/sre-playbook/initial-deployment.md
=> Update links and wording in the initial deployment page

docs/contributor-guide/developer-guide/getting-started.md
Adding more notes on getting Docker setup on Linux computers
=> Updating Docker Section

docs/contributor-guide/developer-guide/dev-testing.md
=> Add dev testing docs

docs/contributor-guide/developer-guide/releasing.md
Added explicit steps so that it's much easier to do each step. Removed things that don't work (yet)
=> Update Release docs to be more explicit and current

docs/.gitbook/assets/api/openapi.json, docs/.gitbook/assets/api/openapi.yaml, docs/SUMMARY.md, docs/it-manual/api/api-specification.md
Adding an example of OpenAPI-generated spec (this was unfortunately created by hand, but maybe we can create it programmatically via Play Framework in the future if this is useful).
=> Add OpenAPI example

docs/contributor-guide/developer-guide/technical-contribution-guide.md
Adds documentation for a CLI git developer flow.
=> Add docs on git workflow

docs/contributor-guide/developer-guide/releasing.md
=> Update Slack Channel Name

docs/it-manual/sre-playbook/terraform-deploy-system.md
Docs change for https://github.com/civiform/civiform-deploy/pull/30
=> Update deploy docs to configure civiform version via config file

docs/contributor-guide/developer-guide/getting-started.md
Include additional manual steps for Intellij setup.
=> Update getting started page

docs/it-manual/sre-playbook/terraform-deploy-system.md
Docs reflect command behavior change in https://github.com/civiform/cloud-deploy-infra/pull/88.
=> Add docs for pgadmin command

docs/contributor-guide/developer-guide/dev-testing.md, docs/contributor-guide/developer-guide/development-standards.md, docs/contributor-guide/developer-guide/frontend-development.md, docs/contributor-guide/developer-guide/getting-started.md, docs/contributor-guide/developer-guide/new-full-time-swe-onboarding-materials.md, docs/contributor-guide/developer-guide/technology-overview.md, docs/contributor-guide/developer-guide/testing.md
* Add section about running TypeScript unit tests.
* Add best practices for TypeScript.,
* Add more info on TypeScript code setup (organization, bundling).
=> Add TypeScript docs

docs/it-manual/sre-playbook/terraform-deploy-system.md
Fix broken links in infra documentation
=> Fix broken links in terraform-deploy-system.md

docs/contributor-guide/developer-guide/releasing.md
Updating Seattle Staging Hostname
=> Updating Seattle Staging Hostname

docs/contributor-guide/developer-guide/deploy-system/testing.md
=> Explicitly number steps

docs/contributor-guide/developer-guide/authentication-providers.md
Fixing typos and bits that were hard to read. This is not a complete revision of the documentation (e.g. I didn't get to the end did not check the correctness of the content), but every little helps for docs improvmements.
=> Improve authentication provider docs

docs/SUMMARY.md, docs/user-manual/civiform-admin-guide/README.md, docs/user-manual/civiform-admin-guide/manage-eligibility.md
Add docs for the eligibility feature ([#3744](https://github.com/civiform/civiform/issues/3744))
Fixes [#4315](https://github.com/civiform/civiform/issues/4315)
=> Add docs for eligibility

docs/user-manual/civiform-admin-guide/add-statuses.md
Changes from https://github.com/civiform/civiform/issues/4174
=> Update add-statuses.md with default status

docs/contributor-guide/developer-guide/feature-flags.md
Updates the Feature Flag docs with the new process from https://github.com/civiform/civiform/pull/4437.
=> Update feature-flags.md with new flag addition process

docs/it-manual/api/program-applications.md
Updating phone export to E164 format
=> Updating phone export to E164 format

docs/contributor-guide/developer-guide/feature-flags.md
Small change to fix example code for overriding feature flags in junit tests.
=> update using feature flags in junit tests

docs/it-manual/sre-playbook/initial-deployment.md
Add more deployment details (mostly by @nbeloglazov @azizova-leyla).
=> Add more deployment details

docs/contributor-guide/developer-guide/deploy-system/prerequisites.md
The option 2 header was one too large. Updating it to be at the same level as option 1
=> Fix the header level

website/public/js/index.js
No substantive code change, just whitespace/newline formatting changes from a newer version of prettier.
=> Rerun prettier for js formatting.

docs/it-manual/api/authentication.md
Update the docs to match the changes from civiform/civiform#4899
Partially completes civiform/civiform#4861
=> Update authentication.md to match new confirmation screen.

docs/it-manual/sre-playbook/monitoring.md
Update the grafana JSON file to include database metrics
See what this looks like here:
Related to: https://github.com/civiform/civiform/issues/4812
=> Update monitoring.md JSON file

.github/renovate.json
Most likely this will just flag github actions that need updating, but still good to check for those.
=> Create basic renovate.json

docs/it-manual/sre-playbook/monitoring.md
Some are now added by default and there are additional variables to include.
https://github.com/civiform/civiform/issues/5109
=> Update docs about RDS alarms

docs/contributor-guide/developer-guide/feature-flags.md
@michaelzetune no worries about not adding the flag, I realized it doesn't actually say anything about that in our docs! Lmk if what I added here works.
=> Add note to add feature flags to staging config

docs/SUMMARY.md, docs/contributor-guide/developer-guide/system-design/data-intake.md
Document where the various pieces of account data originate
=> Add data intake page

docs/user-manual/civiform-admin-guide/manage-translations-for-programs-and-questions.md
=> Update manage-translations-for-programs-and-questions snapshots

docs/SUMMARY.md, docs/contributor-guide/developer-guide/config-vars.md, docs/contributor-guide/developer-guide/development-standards.md
Document the handling of server configuration variables at various locations in the codebase.
Note that this is based on my current understanding, which may be flawed or incomplete.
=> Document the handling of server configuration variables

docs/it-manual/sre-playbook/production-database-access.md, docs/it-manual/sre-playbook/terraform-deploy-system.md
Merging the two spots that were similar into one page and linking to it from the other.
Added a note to not save queries within pgadmin.
=> Updating the docs sections regarding pgadmin

docs/governance-and-management/project-management/on-call-guide/README.md, docs/it-manual/sre-playbook/upgrading-to-a-new-release.md
Update release date from Wednesday to Tuesday
=> Update release date for civic entity docs

docs/it-manual/sre-playbook/terraform-deploy-system.md
https://github.com/civiform/civiform/issues/6462
=> Add documentation about using AWS organizations and AWS cloudshell for CiviForm

docs/it-manual/sre-playbook/terraform-deploy-system.md
https://github.com/civiform/civiform/issues/6419
=> Add info to docs about using config flag

docs/SUMMARY.md
Related to https://github.com/civiform/docs/pull/396/files
=> Small path update

docs/it-manual/sre-playbook/terraform-deploy-system.md
Update our public deploy documentation to better reflect current behavior after this change: https://github.com/civiform/cloud-deploy-infra/pull/295
=> Update info about setup script

docs/user-manual/civiform-admin-guide/using-markdown.md
Related to https://github.com/civiform/civiform/pull/7186
=> add note about markdown in help text and question options

docs/user-manual/civiform-admin-guide/manage-translations-for-programs-and-questions.md
Fixes #7520
It's a protected branch, so I need a code review
=> Update screenshots and instructions to add or edit program translations

docs/it-manual/configure-gis-service.md
Add the expected response format to the Esri documentation
Fixes https://github.com/civiform/docs/issues/464
=> Add expected ESRI response format to docs

docs/it-manual/api/program-applications.md
Add file upload question to API docs
=> Add file upload to api docs

website/public/about/index.html, website/public/css/index.css, website/public/faq/index.html, website/public/news/index.html, website/src/_data/news.json, website/src/about.md, website/src/css/index.scss
Build site from source, including updates from #465, #466, and #469.
=> Build site from source.

website/public/news/index.html, website/src/_data/news.json
Updating CiviForm new, "Seattle celebrates progress..."
=> Updating CiviForm news

docs/it-manual/sre-playbook/production-database-access.md
Explain how to clear the cache, since its not obvious why data doesn't update .
=> Update pgadmin docs to mention cache

website/public/learnmore3/index.html, website/src/learnmore3.md
Please explain the changes you made here.
=> New formatting for Learn More

docs/user-manual/onboarding-guide/programguide
First draft of new onboarding guide for Programs (non-technical).
=> First draft of new onboarding guide for Programs (non-technical)

docs/SUMMARY.md
This is a follow up to https://github.com/civiform/docs/pull/502
=> Quick fix for link issue

.github/pull_request_template.md
Please explain the changes you made here.
=> Fix link in checklist

docs/SUMMARY.md, docs/user-manual/civiform-admin-guide/manage-notifications.md
Please explain the changes you made here.
Fixes https://github.com/civiform/civiform/issues/8436
=> Add program email notifications to admin docs

docs/user-manual/civiform-admin-guide/program-migration.md
Remove note that "validation will be added" since validation is getting added now. Moved some things around so program info is grouped together and question info comes at the bottom of lists.
Related to https://github.com/civiform/civiform/issues/8546
=> Small updates to program-migration docs

website/public/learnmore/index.html, website/src/learnmore.md
Change formatting for new Learn More page to switch from tables to paragraphs, change the checkmark to green, remove the need for bullets.
=> Change formatting for Learn More page

website/public/about/index.html, website/public/contact-new/index.html, website/public/contact/index.html, website/public/deploymentguide/index.html, website/public/faq/index.html, website/public/getstarted-new/index.html, website/public/implementation-guide/index.html, website/public/index.html, website/public/learnmore/index.html, website/public/news/index.html, website/src/_includes/layouts/footer.njk, website/src/_includes/layouts/navigation.njk, website/src/contact-new.md, website/src/getstarted-new.md, website/src/implementation-guide.md
Changed nav bar and footer to point to new versions of changed pages (/contact-new, /getstarted, /learnmore, /implementation-guide).
Changed page template for new pages (/contact-new, /getstarted, /learnmore, /implementation-guide) to ensure that all pages have the same indentation and spacing.
Changed link to /implementation-guide on /learnmore to a button to match the button style on all of the other pages.
=> Website nav bar updates, page spacing, buttonize

docs/user-manual/civiform-admin-guide/program-migration.md
- Remove note about service area eligibility conditions since we support that now
- Add note about limit on program size (related to https://github.com/civiform/civiform/pull/8751
=> update program migration docs

.github/workflows/contributor_response.yml
Testing contributor response action.
=> Testing contributor auto response GH action

.github/workflows/contributor_response.yml
=> Update contributor_response.yml to only have one step

docs/SUMMARY.md
I'm not sure if my earlier file isn't deploying because there is no link to it. Giving this a try.
=> Adding dr file to nav

docs/it-manual/api/authentication.md
The docs should show https:// in the example because it doesn't work otherwise, and it should show a screenshot of the postman setup for easier setup. 
=> Update API docs

docs/it-manual/sre-playbook/disaster-recovery.md
=> Minor fixes to DR page

docs/user-manual/civiform-admin-guide/program-migration.md
Updated the info about program size and added a note about import failing because of missing default translations.
Related to https://github.com/civiform/civiform/issues/9286
=> Update program migration error info

.github/pull_request_template.md
Fix the link to the website docs in our PR template.
=> Fix link to website docs in PR template

docs/it-manual/api/program-applications.md
Added suffix to the api doc now that it's implemented on civiform
Fixes #506
=> Updated program-applications.md with name suffix

docs/user-manual/civiform-admin-guide/using-enumerator-questions-and-screens-in-a-program.md
provide real world application form snippet example with detailed step-by-step instructions on how to use enumerator questions to collect household member information.
Reviewed doc is at: https://docs.google.com/document/d/1vtHfvWycSMMyIRDxCcGR8i0uerAH1nm_laN7cdtecwQ/edit?tab=t.0
Fixes #9308
=> add cookbook example on how to use enumerator to collect household information

docs/user-manual/civiform-admin-guide/manage-api-keys.md
Add a brief context and cross reference of what API key is and how it's used in the CiviForm Admin doc before dive into the details.
N/A
=> Add cross reference to API integration in API key management 

.github/renovate.json, .github/renovate.json5
Renaming to json5 for commenting ability
Please explain the changes you made here.
=> Pin github actions to commit

docs/governance-and-management/project-management/on-call-guide/README.md
Update on call responsibilities to match those on the GH issue
=> Update on call responsibilities to match those on the GH issue

docs/SUMMARY.md, docs/user-manual/civiform-admin-guide/add-categories.md
Adding documentation for CiviForm admins on how to tag a program with categories and on categories in general.
Fixes #8138
=> Documentation for admins on how to tag a program with categories

docs/user-manual/trusted-intermediary-guide/apply-to-a-program.md
The Trusted Intermediary documentation was out of date.  This updates the steps for adding a new client and starting an application for a client.
=> Update TI instructions

docs/governance-and-management/project-management/on-call-guide/README.md
=> Link to PRs for the upgrading demo site step
